server:
  port: 8090
  contextPath: /
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG
  
gragas:  
  zookeeper:
    enabled: true
    connectString: 127.0.0.1:2181
    sessionTimeout: 5000
spring:
  application: 
    name: gragas
  freemarker:
    enabled: true
    template-loader-path: classpath:/webapp/template
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl.html
    
